### ISSUE TITLE
Neue EZ-Pages fehlen im XML Sitemap Generator in der sitemap/sitemapezpages.xml

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/157-modul-sitemap-xml#2]
Hallo webchills,

ich habe mich daran gemacht, die Inhalte des zusätzlichen WordPress Blogs in EZ-Pages zu migrieren.
Dabei ist mir aufgefallen, dass die neuen EZ-Pages vom XML Sitemap Generator v4.1.3 nicht erfasst werden.
Einige ältere aber schon. Ich weiss noch nicht, wieso die alten ja, die neuen noch nicht.

Es gibt übrigens eine neue Version des Plugins bei den Amerikaners.

Ich übernehme da gerne die Übersetzung. Weil das Plugin aber recht umfangreich ist müsste ich Absprache halten, um nichts zu verschlimmbessern.

**Comment by webchills** [comment]
Das Modul ist ok, es muss da nichts geändert werden. Wenn Seiten fehlen, dann prüfe die Sortierreihenfolge dieser Seiten. Es ist so konzipiert, dass nur Seiten mit Sortierreihenfolge > 0 aufgenommen werden. Stelle die Sortierriehenfolge bei den fehlenden Seiten auf einen Wert größer als Null und generiere dann das Feed neu, dann werden auch diese Seiten enthalten sein.

**Comment by webconcept-one** [comment]
Danke für den Hinweis.
Ich musste zusätzlich noch eine Location auswählen. Weil ich nicht alle EZ-Pages automatisch an einer Location verlinkt haben möchte, und auch keine Sidebox verwende, habe ich die Location Sidebox ausgewählt und dafür bei Sortierung einen Wert >0 angegeben.
Jetzt wird die Sitemap korrekt erstellt.
Ich war davon ausgegangen, dass "Sichtbar" auszuwählen genügen würde.
