### ISSUE TITLE
PHP Fatal error: Uncaught Error: Cannot access private property queryFactory::$count_queries in /includes/classes/sitemapxml.php:76

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/157-modul-sitemap-xml#3]
Ich bekomme mit 157g und PHP 8.1.26 einen Fatal Error, wenn ich unter Admin -> Tools -> Sitemap XML unter "Aktion wählen" beide Häkchen setze und dann absende.

`PHP Fatal error: Uncaught Error: Cannot access private property queryFactory::$count_queries in /includes/classes/sitemapxml.php:76`

Die Amerikaner schlagen folgendes vor "if you get errors like...".

`$this->statisticModuleQueries = $db->count_queries;`
->
`$this->statisticModuleQueries = $db->queryCount();`

Für Zeile 76 angewendet 

`$this->statisticTotalQueries = $db->count_queries;`
->
`$this->statisticTotalQueries = $db->queryCount();`

verschiebt es den Fehler auf Zeile 77, die lautet:

`$this->statisticTotalQueriesTime = $db->total_query_time;`

**Comment by webchills** [comment]
Tip:
Nicht immer gibt es für jeden Fix/Änderung eine neue Release oder es wurde vergessen, eine neue damit zu releasen.
Wenn Du bei der Release siehst, dass es seit Release neue Commits gab, dann fixen die wahrscheinlich die Probleme, die in der Release noch enthalten sind.
![commits](https://github.com/zencartpro/157-modul-sitemap-xml/assets/1009695/326562a6-2d64-4924-b9a5-35388edf0de3)
Draufclicken liefert die Commits und dieser hier enthält die geänderte includes/classes/sitemapxml.php, die das behebt:
d3a42199c326bd3eb7a6ad73f1058832cb1206f5

**Comment by webconcept-one** [comment]
Okay,
ich dachte, dass nichts mehr bearbeitet wird, wenn es keine pull requests mehr gibt.
Den gezeigten commit sehe ich leider nirgends. Selbst wenn ich jetzt wissend danach suche.
Ich behalts aber im Hinterkopf.

Edit: jetzt hab ichs gefunden.
